#!/bin/bash
echo ""
echo "███████╗██╗   ██╗███████╗███╗   ███╗  ██████╗███╗   ██╗"
echo "██╔════╝╚██╗ ██╔╝██╔════╝████╗ ████║██╔══ ██╗███╗   ██║"
echo "███████╗ ╚████╔╝ ███████╗██╔████╔██║██║   ██║██╔██╗ ██║"
echo "╚════██║  ╚██╔╝  ╚════██║██║╚██╔╝██║██║   ██║██║╚██╗██║"
echo "███████║   ██║   ███████║██║ ╚═╝ ███║╚██████╔██║ ╚████║"
echo "╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝"
echo "                System Monitor vBasic.0"
echo "                 in progress...by black"
echo "========================================================"
echo ""
display(){
echo -ne "\033[12;OH\033[J"

cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{printf "%.0f", $2}')
echo -n "CPU: ["
for ((i=1;i<=10;i++));do
 if [ $i -le $((cpu_usage/10)) ];then
  echo -n "▓"
 else
  echo -n "░"
fi
done
echo "] ($cpu_usage)%"
echo ""

memory_usage=$(free -m | awk 'NR==2{printf "%.0f", $3*100/$2}')
echo -n "RAM: ["
for ((j=1;j<=10;j++));do
 if [ $j -le $((memory_usage/10)) ];then
  echo -n "▓"
 else
  echo -n "░"
fi
done
echo "] ($memory_usage)%"
echo ""

disk_usage=$(df -h / | awk 'NR==2{print $5}'| tr -d '%')
echo -n "DISK: ["
for k in {1..10};do
 if [ $k -le $((disk_usage/10)) ];then
  echo -n "▓"
 else
  echo -n "░"
fi
done
echo "] ($disk_usage)%"
echo ""
}

while true;do
display
sleep 1
done

